# Site
repository: breadream-io/breadream-io.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 이응완
title: Data Engineer
email: eungwan@gmail.com
# website: www.github.com/breadream-io/breadream-io.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  breadream-io
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | 
  안녕하세요, 빵을 사랑하는 15년차 개발자 이응완입니다.
  
  <mark>백엔드 개발자</mark>로 시작해 <mark>모바일 앱 개발</mark>을 거쳐 현재는 <mark>데이터 엔지니어</mark>로 활동하고 있습니다.
  
  효율성을 높이는 자동화 툴과 확장 가능한 코드 개발에 열정을 쏟고 있으며,
  
  ETL 및 데이터 파이프라인 구축에서 깊은 전문성을 보유하고 있습니다.
  
  Java, JavaScript, Python, Swift, Scala, Objective-C 언어에 익숙하며, 
  
  Kafka, Hadoop, Spark, Hive를 포함한 iOS와 Android 플랫폼을 활용합니다.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag